### ISSUE TITLE
Bundling the code

### ISSUE THREAD

**Issue by 625alex** [GartorwareCorp/firebase-util#1]
First of all, thank you for attempting to migrate this utility to Firebase 3.

My project heavily relies on firebase-util and I can't, for the life of me, figure out how to bundle up the source files.

I tried `gulp bundle` task, but I get errors I can't figure out how to resolve.

Could you please add instructions how to bundle or add the dist file?

Thank you in advance.

**Comment by gartorware** [comment]
Sorry for late response, I have been away.

Bundle task is still the same as the original firebase-util you just need to do the usual:
- git clone ...
- cd ./firebase-util
- npm install
- bower install
- gulp bundle

After this, you should see the dist folder with the updated code.

What errors are you getting? I have tried this again with success using a clean git clone of the fork. Maybe is a problem with SO version, I have tried with Linux Ubuntu x64. What SO do you have?

**Comment by gartorware** [comment]
Anyway if you dont want to mess with bundle you could try to install it directly with bower:
`bower uninstall firebase-util`
then
`bower install https://github.com/GartorwareCorp/firebase-util.git#v0.3.0gt`

But **be careful**, this will replace your current installation of firebase-util with code of this fork, so it will stop working with v2 firebase api and maybe you have to rollback.

Another option if you just want the code to manually install it, it's to go to releases section and download latest v0.3.0gt of this fork:
https://github.com/GartorwareCorp/firebase-util/releases/tag/v0.3.0gt 

Remember that API has changed, you can see changes in main Readme.md

Please, remember too that this fork is a work in progress trying to migrate firebase-util to firebase 3. I'm still working on tests so nobody can assure you this is errors free ;) Any feedback will be much appreciated. 

Regards.

**Comment by 625alex** [comment]
Thank you for for detailed response.

The `bundle` task is failing for me. I opened a ticket with the original project https://github.com/firebase/firebase-util/issues/99. I might be doing something wrong though, this is all new to me.

I will try to install directly as you described above.

I'm well aware that the API has changed. My application is heavily dependent on this utility, but the underlying code is way above my head. I was in process of refactoring my code to remove this dependency or replace it with https://github.com/mismith/angularfire-helper. If your fork of firebase-util mostly works, I will be very happy.

Thank you for migrating the utility to FB3.

**Comment by 625alex** [comment]
I tried the direct installation mentioned above
`bower install https://github.com/GartorwareCorp/firebase-util.git#v0.3.0gt`.

It appears to be working. I will let you know if anything breaks.

Thanks
