### ISSUE TITLE
ref.on is not a function

### ISSUE THREAD

**Issue by macias67** [GartorwareCorp/firebase-util#10]
I have this:
![captura](https://cloud.githubusercontent.com/assets/1738146/19224455/efad9128-8e4b-11e6-942c-5d6dc7d77ba7.PNG)

In the console shows me an error: `ref.on is not a function`.

**Comment by gartorware** [comment]
Mmmm good catch. The problem is here, change this line:
`var ref = norm.ref;` 
To this one (note the parenthesis):
`var ref = norm.ref();`

I will have a look into that since the syntax should be like you are writing it. 
Thank you very much for the report!
