### ISSUE TITLE
s.key is not a function error

### ISSUE THREAD

**Issue by nurfgun** [GartorwareCorp/firebase-util#11]
<img width="2048" alt="screen shot 2016-10-17 at 11 50 51 pm" src="https://cloud.githubusercontent.com/assets/3580630/19442535/91c1e8fa-94c4-11e6-8fcc-c60a42c65690.png">

```
FIREBASE WARNING: Exception was thrown by user callback. TypeError: s.key is not a function
    at http://localhost:8888/schoolbelle-board/bower_components/firebase-util/dist/firebase-util.js:1876:16
```

I was using Scroll with Normalized collection.

```
  hasChild: function(snaps, key) {
    return util.contains(snaps, function(s) {
      return s.key() === key;
    });
  },


  getChildSnaps: function(snapsArray, recordId) {
    return util.filter(snapsArray, function(s) {
      return s.key() === recordId;
    });
  },
```

should it be changed to 's.key' without parenthesis?

ps. thanks for your effort! I'm benefiting greatly from your work 👍

**Comment by gartorware** [comment]
Yeah! Now the key is retrieved as a property instead of a function. Remove the parenthesis `s.key === key` , it should work!

Regards!
