### ISSUE TITLE
Paginate error when orderBy $key

### ISSUE THREAD

**Issue by maxinminax** [GartorwareCorp/firebase-util#2]
As the title, it have a error when go to page > 1. 
`Uncaught Error: Query: When ordering by key, you may only pass one argument to startAt(), endAt(), or equalTo()`

**Comment by gartorware** [comment]
Hmm curious... When ordering by another value it doesn't happen... Firebase 3 force us to only pass one argument to these query functions when ordering by key. 
I have updated code to fix this.

**Comment by gartorware** [comment]
I bundle v0.3.1gt with this issue fixed :dancer: 

bower install https://github.com/GartorwareCorp/firebase-util.git#v0.3.1gt
