### ISSUE TITLE
firebase.util is undefined

### ISSUE THREAD

**Issue by grrrian** [GartorwareCorp/firebase-util#3]
Thanks for your fork! I must be doing something wrong because my firebase.util is undefined.

I imported with `bower install https://github.com/GartorwareCorp/firebase-util.git#v0.3.0gt`, and i added `<script src="lib/firebase-util/src/fbutil.js" inline></script>` to my index.html.

When I print `window.firebase` i get a nice object with SDK_VERSION 3.2.0 but no `util` property. What am I doing wrong?

**Comment by gartorware** [comment]
Hi! Thank you for your comment!

In order to have a working firebase-util you must add the js from the **dist** folder, not the one in src (these are unbundled sources). For instance: 
`<script src="lib/firebase-util/dist/firebase-util.min.js"></script>`

Hope it helps!

**Comment by grrrian** [comment]
Thanks! That was pretty dumb on my part.
