### ISSUE TITLE
Uncaught Error: Cannot find module 'firebase'

### ISSUE THREAD

**Issue by medua** [GartorwareCorp/firebase-util#4]
Hello,

sorry for that but I have an issue while including this version of firebase-util.
It gives me the same error like the latest official 0.2.5.

I tried to install it manually, by bundling and by installing it with bower directly.
All of them gives me the error "Uncaught Error: Cannot find module 'firebase'"

Its definitely my fault but I don't know what i'm doing wrong.

**Comment by gartorware** [comment]
Hi!

Make sure you have actually included the Firebase libs in your project! This version of firebase-util requires firebase v3.x, it doesn't work with v2.x, so please, make sure you've included the right version.

In your index you should have something like:
`<script src="lib/firebase/firebase.js"></script>`
`<script src="lib/angularfire/dist/angularfire.js"></script>`
`<script src="lib/firebase-util/dist/firebase-util.min.js"></script>`

Regards!
