### ISSUE TITLE
Joining data using firebase-util not working

### ISSUE THREAD

**Issue by md-rashid** [GartorwareCorp/firebase-util#5]
I have the following data structure in firebase

```
firebase
    cart
        <userid>
            <productid>
                productid:<productid>
                quantity:<quantity>
    products   
        <productid>
            name:<name>
            price:<price>
            productid:<productid>
```

I am trying to do a join here using normalized collection from fb-util.

```
var norm = new firebase.util.NormalizedCollection(
        firebase.database().ref().child('cart/121'),
        firebase.database().ref().child('products')
    ).select(
        {key: '121.productid', alias: 'CartProductId'},
        'products.productid',
        '121.quantity',
        'products.price',
        'products.name'
    ).ref();

    // run it and see what we get
    norm.on('value', function(snap) {
        console.log('adding new value!', snap.val());
    });

    var cart = $firebaseArray(norm);
    console.log(cart);
```

However, my cart shows up as empty (of length 0) when printing to console. Also, I dont see any console logs with 'adding new value!'

Any idea whats going on here ?

Thanks.

**Comment by gartorware** [comment]
Hi!

That's weird, your code seems to be right...

Is the console showing any error? If it doesn't you may be facing a permission problem. To discard this possibility just add:
`".read":"true",`
`".write":"true"`
to the top level of your security rules and try again. Remember to remove them after the test!

**Comment by marashid** [comment]
I fixed the issue. Thanks. :)

**Comment by gartorware** [comment]
Ok! I close the issue!

**Comment by zipli** [comment]
@marashid , what was the solution you implemented? I have similar problem mentioned [here](https://github.com/GartorwareCorp/firebase-util/issues/8)
