### ISSUE TITLE
firebase.util.NormalizedCollection is not a constructor OR firebase.util.Scroll is not a constructor 

### ISSUE THREAD

**Issue by MathieuDuboy** [GartorwareCorp/firebase-util#7]
I have this 2 issues in my Ionic Project. I tried to build an infinite-list with firebase-util (NormalizedCollection and Scroll method).
But when I add this file :

```
    <script src="lib/firebase-util/dist/firebase-util.js"></script>
    <script src="lib/firebase-util/dist/firebase-util-paginate.min.js"></script>
    <script src="lib/firebase-util/dist/firebase-util-normalize.min.js"></script>
```

I get this error : firebase.util.Scroll is not a constructor 
And when I switched the 2 last, I get this error : 
firebase.util.NormalizedCollection is not a constructor

What is wrong with that ? 
Here is my angularJs code :

```
 var ref = firebase.database().ref();
 var nc = new firebase.util.NormalizedCollection(
   ref.child('accounts/' + $localStorage.accountId + '/demandes'),
   [ref.child('demandes'), 'widget2'])
   .select( 'widget2.vues', 'widget2.duree', 'widget2.derniere_modification', 'widget2.reponses', 'widget2.exp', 'widget2.ajout_le', 'widget2.localisation').
   filter(function(data, key, priority) {
     return data.reponses && data.reponses.$value !== null; 
   }).ref();
 $scope.items = $firebaseArray(nc);
 var scrollRef = new firebase.util.Scroll(nc, 'durre');
 scrollRef.scroll.next(3);

 $scope.loadMore = function() {
   scrollRef.scroll.next(1);
   $scope.$broadcast('scroll.infiniteScrollComplete');
 };
```

These two files can't work together ? Each method works very well but not together ...

**Comment by gartorware** [comment]
Hi!

You don't need to include those 2 last scripts, just the first one! (In fact, you mustn't)
`<script src="lib/firebase-util/dist/firebase-util.min.js"></script>`

Then you can use NormalizedCollection and Scroll as usual.

Regards!

**Comment by MathieuDuboy** [comment]
Oh ... that was stupid ! Thank you so much, it works really Good now :)
