### ISSUE TITLE
Could not join

### ISSUE THREAD

**Issue by zipli** [GartorwareCorp/firebase-util#8]
Hello,
I tried to implement simple join with using sample data that kato had given an answer to [this question](http://stackoverflow.com/questions/30299972/joining-data-between-paths-based-on-id-using-angularfire) but it did not work.
here is my json data:

> "work" : {
>     "cars" : {
>       "DeLorean" : {
>         "model" : "DeLorean",
>         "year" : 1975
>       }
>     },
>     "users" : {
>       "kato" : {
>         "cars" : {
>           "DeLorean" : true
>         }
>       }
>     }
>   }

I have a service and inside of it there is a function uses NormalizedCollection:

> angular.
>   module('core.sales')
>   .service('SalesService', function ($firebaseArray, $firebaseObject, UsersService) {
> ....... 
> this.getAllSalesJoin = function () {
>       var sales;
>       var ref = firebase.database().ref();
>       var nc = new firebase.util.NormalizedCollection(
>         ref.child('work/users/kato'),
>         ref.child('work/cars')
>       )
>       .select(  
>         'cars.model',
>         'cars.year'
>       )
>       .ref();
>       sales = $firebaseObject(nc);  
>       return sales;
>     };

when I print the returned object using `<pre>{{$ctrl.allSales | json}}</pre>`
it prints below, (does not print model or year of the joined object)

> {
>   "$id": "[kato][cars]",
>   "$priority": null,
>   "cars": {}
> }

**Comment by gartorware** [comment]
Hi, 

I think you are not using it rightly. Try to replace your NormalizedCollection for this one:

```
var nc = new firebase.util.NormalizedCollection(
ref.child('work/users/kato/cars'),
[ref.child('work/cars'), 'katoCars']
)
.select(
'katoCars.model',
'katoCars.year'
)
.ref();

sales = $firebaseObject(nc);
```

**Comment by zipli** [comment]
Yes it worked !
10x for the quick reply.
