### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by yacaeh** [GartorwareCorp/firebase-util#9]
Hi I'm using AngularJS and get this error 
fbutil.js:7Uncaught ReferenceError: require is not defined
I've included Firebase 3 and angular fire Like this below. 
Should I include something else too? And if there's min.js can you provide link for it?

```
<script src="https://www.gstatic.com/firebasejs/3.3.0/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
------------------------------------------------------
  };
  firebase.initializeApp(config);
</script>
<!-- AngularFire -->
<script src="https://cdn.firebase.com/libs/angularfire/2.0.2/angularfire.min.js"></script>
<script src="lib/firebase-util-master/src/fbutil.js"></script>    

```

**Comment by gartorware** [comment]
Hi

You must include the dist file, not the source one. There is not dist files in master branch, you must use a released version, either installing it with bower or downloading it from [releases](https://github.com/GartorwareCorp/firebase-util/releases). Once downloaded you can add the minified version inside dist folder.
